### ISSUE TITLE
chuffed does not compile with clang

### ISSUE THREAD

**Issue by krzku** [geoffchu/chuffed#4]
Hi!

First, thanks for making the code available for this great solver. 

I can compile your software on Linux with GNU g++ 4.8.1 but I have problems to compile it under Mac OS 10.10 with the clang compiler. Clang follows the C++ standard very strictly and generates the following error.

In file included from /Users/kris/research/chuffed-master/trunk/chuffed/vars/int-var.c:3:
In file included from /Users/kris/research/chuffed-master/trunk/./chuffed/mip/mip.h:6:
/Users/kris/research/chuffed-master/trunk/./chuffed/core/propagator.h:114:15: error: use of
      undeclared identifier 'Clause_new'
  Clause *c = Clause_new(ps);
              ^
1 error generated.

It seems to be connected tot he problem of namespace specified in C++ standard in chapter "7.3.1.2 Namespace member definitions". You define a friend class Clause_new within class Clause that is **not visible** outside the class according to the standard. I did not tried but the code might not be compiled in newer versions (>= 5) of gnu compiler either.

Do you plan to make necessary changes?

Best,
/Kris

**Comment by schutta** [comment]
It should be fixed in the new version available at [Chuffed](https://github.com/chuffed).
