### ISSUE TITLE
git layout is wrong

### ISSUE THREAD

**Issue by msoos** [geoffchu/chuffed#5]
Hi,

Welcome to GitHub! I'm glad you are here :) I develop CryptoMiniSat, a premier SAT solver. Along with MiniSat, these two are the only ones on GitHub or indeed on any open development environment. I have about 3-4 years of experience with using GitHub. So, here is some advice, please don't take it wrongly :)

I think your git dir layout is wrong... You should not put binaries into GIT. Instead, on GitHub you can make "releases". Just add a git tag, push it to github, and then create a release from it. You can attach binaries to releases. This makes a _lot_ more sense, since obviously you will not be updating your binaries with all the changes you make to the sourcecode. Also, keeping large binary files in git that are supposed to change every so often is not a good idea to do. Actually, it's a pretty bad idea. So, I suggest to:

1) remove binary directory
2) create release
3) attach binaries to release

To be honest, adding the binaries is such a bad idea that I personally would delete the repo and re-create it with the same name, but without the binaries. Otherwise whoever wants to clone your repo will need to keep the binaries in the history even if you delete them (history is forever). Cloning a repo is supposed to be cheap so people can hack on it. Putting lots of binaries in makes it very hard to clone and play.

I know the above sounds like criticism, but it's constructive and in the long run, it will pay out. It takes time to get used to the git/github way of doing things. It's great though :)

Good luck!

Mate

**Comment by schutta** [comment]
It should be fixed in the new version available at [Chuffed](https://github.com/chuffed).
