### ISSUE TITLE
Feature request: disjunctive constraint with flexible processing times

### ISSUE THREAD

**Issue by skosch** [geoffchu/chuffed#6]
Hi,

thanks for sharing chuffed—I'm thrilled it's available on github!
Is there a chance we'll get a disjunctive constraint with variable processing times (i.e. a "proper" MiniZinc-style `disjunctive`)? 

Seb

**Comment by schutta** [comment]
The new version available at [Chuffed](https://github.com/chuffed) contains a disjunctive constraint with variable processing times in Chuffed's MiniZinc library. Internally, it will be map to the cumulative constraint.
