### ISSUE TITLE
array_bool_xor not found with MiniZinc 2.0.12

### ISSUE THREAD

**Issue by glebbelov** [geoffchu/chuffed#7]
... e.g., on the Challenge 2012 instance ../challenge_from2012/mznc12-problems/parity-learning/parity-learning.mzn ../challenge_from2012/mznc12-problems/parity-learning/44_22_5.2.dzn

Possible add-on to redefinitions.mzn:
predicate array_bool_xor(array[int] of var bool: a) =
     let { var 0..(length(a)-1) div 2: m,
           var 1..((length(a)-1) div 2)*2+1: ss = sum(i in index_set(a))( bool2int(a[i]) ) }
     in
       ss == 1 + 2 \* m;

**Comment by schutta** [comment]
It should be fixed in the new version available at [Chuffed](https://github.com/chuffed).
